- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
    - include: ./tasks/init.yml
    - include: ./tasks/bspwm.yml
    - include: ./tasks/apps.yml
    - include: ./tasks/nvim.yml
    - include: ./tasks/dotfiles.yml
    - include: ./tasks/node.yml
    - include: ./tasks/rust.yml
