- name: Setup RPM fusion
  become: yes
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    disable_gpg_check: yes
  tags:
    - install
    - app-setup
- name: Add repos
  become: yes
  shell:
    cmd: |
      dnf install dnf-plugins-core
      dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
      rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
      dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
  tags:
    - install
    - app-setup
