- name: Setup RPM fusion
  become: yes
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    disable_gpg_check: yes
  tags:
    - install
    - apps
- name: Add repos
  become: yes
  shell:
    cmd: |
      dnf install dnf-plugins-core
      dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
      rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  tags:
    - install
    - apps
- name: Download Slack
  get_url:
    url: https://downloads.slack-edge.com/releases/linux/4.23.0/prod/x64/slack-4.23.0-0.1.fc21.x86_64.rpm
    dest: /tmp/slack-4.23.0.rpm
  tags:
    - install
    - apps
- name: Download tidal-hifi
  get_url:
    url: https://github.com/Mastermindzh/tidal-hifi/releases/download/2.7.1/tidal-hifi-2.7.1.x86_64.rpm
    dest: /tmp/tidal-hifi-2.7.1.rpm
  tags:
    - install
    - apps
- name: Download xppen driver
  get_url:
    url: https://www.xp-pen.com/download/file/id/1948/pid/523/ext/rpm.html
    dest: /tmp/xppen-3.2.1.211019-1.rpm
  tags:
    - install
    - apps
- name: Download Zoom
  get_url:
    url: https://zoom.us/client/latest/zoom_x86_64.rpm
    dest: /tmp/zoom.rpm
  tags:
    - install
    - apps
- name: Download DBeaver
  get_url:
    url: https://dbeaver.io/files/dbeaver-ce-latest-stable.x86_64.rpm
    dest: /tmp/dbeaver-latest.rpm
  tags:
  - install
  - apps
- name: Remove Conflicting Apps
  become: yes
  dnf:
    name:
      - podman
      - buildah
    state: absent
  tags:
    - install
    - apps
- name: Install Apps
  become: yes
  dnf:
    name:
      - xournalpp
      - geary
      - krita
      - discord
      - thunar
      - alacritty
      - brave-browser
      - ImageMagick
      - tmux
      - docker-ce
      - docker-compose
      - docker-ce-cli
      - containerd.io
  tags:
    - install
    - apps
- name: Install Apps (no GPG)
  become: yes
  dnf:
    name:
      - /tmp/slack-4.23.0.rpm
      - /tmp/tidal-hifi-2.7.0.rpm
      - /tmp/xppen-3.2.1.211019-1.rpm
      - /tmp/zoom.rpm
      - /tmp/dbeaver-latest.rpm
    disable_gpg_check: yes
  tags:
    - install
    - apps
- name: Start Docker
  become: yes
  shell:
    cmd: |
      systemctl start docker.service
      systemctl start containerd.service
      systemctl enable docker.service
      systemctl enable containerd.service
  tags:
    - install
    - apps
- name: Use Docker without sudo
  become: yes
  shell:
    cmd: usermod -aG docker $USER
  tags:
    - install
    - apps
