- name: Get tidal-hifi url
  shell:
    cmd: curl -s https://api.github.com/repos/Mastermindzh/tidal-hifi/releases | grep browser_download_url | grep 'x86_64[.]rpm' | head -n 1 | cut -d '"' -f 4
  register: tidalhifiurl
  tags:
    - install
    - apps
    - tidal
- name: Download tidal-hifi
  get_url:
    url: "{{ tidalhifiurl.stdout }}"
    dest: /tmp/tidal-hifi.rpm
  tags:
    - install
    - apps
    - tidal
- name: Install tidal-hifi (no GPG)
  become: true
  dnf:
    name:
      - /tmp/tidal-hifi.rpm
    disable_gpg_check: yes
  tags:
    - install
    - apps
    - tidal
- name: Get stripe-cli url
  shell:
    cmd: curl -s https://api.github.com/repos/stripe/stripe-cli/releases | grep browser_download_url | grep 'amd64[.]rpm' | head -n 1 | cut -d '"' -f 4
  register: stripecliurl
  tags:
    - install
    - apps
- name: Download stripe-cli
  get_url:
    url: "{{ stripecliurl.stdout }}"
    dest: /tmp/stripe-cli.rpm
  tags:
    - install
    - apps
# - name: Download xppen driver
#   get_url:
#     url: https://www.xp-pen.com/download/file/id/1948/pid/523/ext/rpm.html
#     dest: /tmp/xppen.rpm
#   tags:
#     - install
#     - apps
- name: Download Zoom
  get_url:
    url: https://zoom.us/client/latest/zoom_x86_64.rpm
    dest: /tmp/zoom.rpm
  tags:
    - install
    - apps
- name: Remove Conflicting Apps
  become: true
  dnf:
    name:
      - buildah
    state: absent
  tags:
    - install
    - apps
- name: Install Apps
  become: true
  dnf:
    name:
      - xournalpp
      - geary
      - krita
      - thunar
      - alacritty
      - kitty
      - brave-browser
      - ImageMagick
      - tmux
      - podman
      - podman-compose
      - gh
      - flameshot
      - community-mysql
      - syncthing
      - playerctl
      - task
      - timew
  tags:
    - install
    - apps
- name: Install Apps (no GPG)
  become: true
  dnf:
    name:
      - /tmp/tidal-hifi.rpm
      - /tmp/stripe-cli.rpm
      # - /tmp/xppen.rpm
      - /tmp/zoom.rpm
    disable_gpg_check: yes
  tags:
    - install
    - apps
