- name: Install Packages (BSPWM)
  become: yes
  dnf:
    name:
    - bspwm
    - sxhkd
    - nitrogen
    - picom
    - polybar
    state: latest
  tags:
  - install
  - bspwm
- name: Install pip
  become: yes
  dnf:
    name: python3-pip
  tags:
  - install
  - bspwm
- name: Install pywal
  pip:
    name: pywal
  tags:
  - install
  - bspwm
