- name: Install Packages (BSPWM)
  become: true
  dnf:
    name:
      - bspwm
      - sxhkd
      - nitrogen
      - polybar
      - rofi
      - autoconf
      - automake
      - cairo-devel
      - fontconfig
      - gcc
      - libev-devel
      - libjpeg-turbo-devel
      - libXinerama
      - libxkbcommon-devel
      - libxkbcommon-x11-devel
      - libXrandr
      - pam-devel
      - pkgconf
      - xcb-util-image-devel
      - xcb-util-xrm-devel
    state: latest
  tags:
    - install
    - bspwm

- name: Picom Deps
  become: true
  dnf:
    name:
      - dbus-devel
      - gcc
      - git
      - libconfig-devel
      - libdrm-devel
      - libev-devel
      - libX11-devel
      - libX11-xcb
      - libXext-devel
      - libxcb-devel
      - libGL-devel
      - libEGL-devel
      - meson
      - pcre-devel
      - pcre2-devel
      - pixman-devel
      - uthash-devel
      - xcb-util-image-devel
      - xcb-util-renderutil-devel
      - xorg-x11-proto-devel
    state: latest
  tags:
    - install
    - bspwm

- name: Clone Picom
  git:
    repo: "https://github.com/ibhagwan/picom"
    dest: "{{ lookup('env', 'HOME') }}/.sources/picom"
    depth: 1
    version: next-rebase
  tags:
    - install
    - bspwm

- name: Build Install Picom
  become: true
  shell: |
    "cd {{ lookup('env', 'HOME') }}/.sources/picom"
    git submodule update --init --recursive
    meson setup --buildtype=release . build
    ninja -C build install
  tags:
    - install
    - bspwm
