- name: Set git name
  git_config:
    name: user.name
    scope: global
    value: "Braydon Hall"
  tags:
    - install
    - git
- name: Set git email
  git_config:
    name: user.email
    scope: global
    value: "40751395+nobrayner@users.noreply.github.com"
  tags:
    - install
    - git
- name: Set git init branch to main
  git_config:
    name: init.defaultBranch
    scope: global
    value: "main"
  tags:
    - install
    - git
- name: Prune on pull/fetch
  git_config:
    name: remote.origin.prune
    scope: global
    value: true
  tags:
    - install
    - git
- name: Prune on pull/fetch
  git_config:
    name: pull.rebase
    scope: global
    value: true
  tags:
    - install
    - git
