- name: Install LTS Nodejs
  shell:
    cmd: '~/.sources/asdf/bin/asdf install nodejs'
  tags:
    - install
    - node
- name: Install pnpm
  shell:
    cmd: 'curl -fsSL https://get.pnpm.io/install.sh | sh -'
  tags:
    - install
    - pnpm
    - node
