- name: Install LTS Nodejs
  shell:
    cmd: '~/.sources/asdf/bin/asdf install nodejs'
  tags:
    - install
    - node
- name: Install yarn
  shell:
    cmd: 'curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo'
  tags:
    - install
    - node
- name: Install pnpm
  shell:
    cmd: 'curl -fsSL https://get.pnpm.io/install.sh | sh -'
  tags:
    - install
    - node
