- name: Install node
  become: true
  dnf:
    name:
      - nodejs
  tags:
    - install
    - node
- name: Install yarn
  become: true
  npm:
    name: yarn
    global: yes
  tags:
    - install
    - node
