- name: Install zsh
  become: yes
  dnf:
    name:
      - zsh
      - util-linux-user
  tags:
    - install
    - zsh
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags:
    - install
    - zsh
